development:
  adapter: postgresql
  database: StyleMe_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: StyleMe_dev
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: StyleMe_dev
  pool: 5
  timeout: 5000
